# Generated by Django 2.2 on 2019-05-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sis',
            name='birthDate',
            field=models.CharField(default=45, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sis',
            name='gender',
            field=models.CharField(default=6, max_length=20),
            preserve_default=False,
        ),
    ]
